# Native AMD64 target settings
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

# ARM64 target settings
[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc"]

# ARM64 GNU target (alternative)
[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

# Global build settings
[build]
rustflags = ["-C", "target-feature=+crt-static"]
